spring.jpa.database-platform: com.floxd.hogwartsbot.config.SQLDialect
spring.jpa.hibernate.ddl-auto: validate

spring.datasource.url: jdbc:sqlite:db/hogwartsbot.db
spring.datasource.driver-class-name: org.sqlite.JDBC
spring:
  jpa:
    defer-datasource-initialization: false
    show-sql: true
  flyway:
    url: jdbc:sqlite:db/hogwartsbot.db
    user: admin
    password: admin
    schemas:
      - main
    enabled: true
    baseline-on-migrate: true

sql.init.mode: always

spring.datasource.username: admin
spring.datasource.password: admin

management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true

# uncomment to see all twitch websocket messages
# logging.level.com.floxd.hogwartsbot.service: DEBUG

logging.level.org.hibernate.tuple.entity.PojoEntityTuplizer: ERROR
logging.level.org.flywaydb: DEBUG
